-- MySQL Script generated by MySQL Workbench
-- Thu Jul 31 21:53:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simp_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `simp_db` ;

-- -----------------------------------------------------
-- Schema simp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simp_db` DEFAULT CHARACTER SET utf8 ;
USE `simp_db` ;

-- -----------------------------------------------------
-- Table `simp_db`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simp_db`.`USERS` ;

CREATE TABLE IF NOT EXISTS `simp_db`.`USERS` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_USER`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
